# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_subgraph_internal <- function(edgelist, signals, gorder, module_size, niter, edge_penalty) {
    .Call('_mcmcRanking_sample_subgraph_internal', PACKAGE = 'mcmcRanking', edgelist, signals, gorder, module_size, niter, edge_penalty)
}

sample_llh_internal <- function(edgelist, signals, likelihood, niter, fixed_size, start_module, edge_penalty) {
    .Call('_mcmcRanking_sample_llh_internal', PACKAGE = 'mcmcRanking', edgelist, signals, likelihood, niter, fixed_size, start_module, edge_penalty)
}

mcmc_sample_internal <- function(edgelist, signals, likelihood, fixed_size, niter, start_module, edge_penalty) {
    .Call('_mcmcRanking_mcmc_sample_internal', PACKAGE = 'mcmcRanking', edgelist, signals, likelihood, fixed_size, niter, start_module, edge_penalty)
}

mcmc_onelong_internal <- function(edgelist, signals, likelihood, fixed_size, module_size, start, niter, edge_penalty) {
    .Call('_mcmcRanking_mcmc_onelong_internal', PACKAGE = 'mcmcRanking', edgelist, signals, likelihood, fixed_size, module_size, start, niter, edge_penalty)
}

mcmc_onelong_frequency_internal <- function(edgelist, signals, likelihood, fixed_size, module_size, start, niter, edge_penalty) {
    .Call('_mcmcRanking_mcmc_onelong_frequency_internal', PACKAGE = 'mcmcRanking', edgelist, signals, likelihood, fixed_size, module_size, start, niter, edge_penalty)
}

probabilistic_rank_internal <- function(edgelist, df_nodes) {
    .Call('_mcmcRanking_probabilistic_rank_internal', PACKAGE = 'mcmcRanking', edgelist, df_nodes)
}

